#ifndef _UEFI_PROTOCOLS_DEVICEPATHPROTOCOL_H
#define _UEFI_PROTOCOLS_DEVICEPATHPROTOCOL_H

#include "../Common.h"

#define EFI_DEVICE_PATH_PROTOCOL_GUID { 0x09576e91, 0x6d3f, 0x11d2, { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b } }

typedef struct _EFI_DEVICE_PATH_PROTOCOL {
    UINT8 Type;
    UINT8 SubType;
    UINT8 Length[2];
} EFI_DEVICE_PATH_PROTOCOL;

#define HARDWARE_DEVICE_PATH 1
#define HW_PCI_DP 1

typedef struct _PCI_DEVICE_PATH {
    EFI_DEVICE_PATH_PROTOCOL Header;
    UINT8 Function;
    UINT8 Device;
} PCI_DEVICE_PATH;

#define HW_PCCARD_DP 2

typedef struct _PCCARD_DEVICE_PATH {
    EFI_DEVICE_PATH_PROTOCOL Header;
    UINT8 FunctionNumber;
} PCCARD_DEVICE_PATH;

#define HW_MEMMAP_DP 3

typedef struct _MEMMAP_DEVICE_PATH {
    EFI_DEVICE_PATH_PROTOCOL Header;
    UINT32 MemoryType;
    EFI_PHYSICAL_ADDRESS StartingAddress;
    EFI_PHYSICAL_ADDRESS EndingAddress;
} MEMMAP_DEVICE_PATH;

#endif // _UEFI_PROTOCOLS_DEVICEPATHPROTOCOL_H
